#!/usr/bin/env python3
"""Draw the 16x16 textures for the Arc-style loot line (scripts/gen-arc-loot.py).

Each sprite is an ASCII map plus a palette ('.' = transparent). A dark outline
is added automatically around every silhouette (darkened neighbour colour), in
the same style as the existing Oraxen-converted item textures.

Usage:
  python scripts/gen-arc-loot-textures.py                 # write into the Nexo pack
  python scripts/gen-arc-loot-textures.py --out DIR --sheet sheet.png   # preview only
"""
import argparse
import os

from PIL import Image, ImageDraw

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(REPO, "server", "plugins", "Nexo", "pack", "external_packs", "Oraxen",
                    "assets", "minecraft", "textures")

METAL = {"a": "#e4e8ef", "b": "#a9afba", "c": "#6d7380", "o": "#454a55"}
RARITY_TINT = {"common": ("#9aa3b0", "#d7dde6"), "uncommon": ("#3fae5a", "#9be38f"),
               "rare": ("#3b6fd8", "#8fc0ff"), "legendary": ("#d99a1e", "#ffe27a")}

SPRITES = {
    # ---------------------------------------------------------------- salvage
    "scrap_plating": ({**METAL, "r": "#b8662f", "R": "#8a4521"}, """
................
..........bb....
......bbbbaab...
....bbaaaaaabb..
...baaaaraaaab..
..baaoaaaRaaab..
..baaaaaaaaoab..
..bcaaaaaaaaacb.
...bcaaarraacb..
....bcaaaaacb...
.....bbccccb....
.......bbb......
"""),
    "frayed_wiring": ({"s": "#8b8f99", "v": "#c3c7cf", "c": "#e0874a", "C": "#a65a2c",
                       "h": "#ffc38a"}, """
....ssssssss....
....svvvvvvs....
.....cCcCcC.....
.....CcCcCc.....
.....cCcCcC.....
.....CcCcCc.....
.....cCcCcC.....
.....CcCcCc.....
....svvvvvvs....
....ssssssssc...
.............c..
............h.h.
...........h..h.
"""),
    "polymer_goo": ({"w": "#ffffff", "a": "#a8f7cf", "b": "#4fd69a", "c": "#23946a"}, """
......aaaa......
....aabbbbaa....
...abbwwbbbba...
...abwbbbbbba...
..abbbbbbbbbba..
..abbbbbbbbbcba.
..bbbbbbbbbcccb.
...bbbbcbbccccb.
....cbccccccc...
.....c...cc.....
"""),
    "coolant_cell": ({"m": "#6d7380", "n": "#b9bfc9", "g": "#cfe9f2", "b": "#3fd3ea",
                      "d": "#1e8fb0", "w": "#ffffff"}, """
.....mmmmmm.....
....mnnnnnnm....
....gbbbbbbg....
....gwbbbbbg....
....gwbbbbbg....
....gbbbbbdg....
....gbbbbbdg....
....gbbbbbdg....
....gbbbbbdg....
....gbbbbddg....
....mnnnnnnm....
.....mmmmmm.....
"""),
    "glitch_cloth": ({"a": "#c28af0", "b": "#9b5de5", "c": "#6c3aa8", "p": "#f472b6",
                      "q": "#22d3ee"}, """
...aaaaaaaaaa...
..abbbbbbbbbba..
..abpbbbbbbbba..
..abbbbbbbbbba..
..cccccccccccc..
..abbbbbbbbbba..
..abbbbbpppbbaq.
..abbbbbbbbbba..
..cccccccccccc..
.qabbbbbbbbbba..
..abbbbbbbbbbc..
...cccccccccc...
"""),
    "circuit_core": ({"y": "#f5c542", "g": "#1f5f3a", "G": "#2f8f55", "K": "#2a2d36",
                      "k": "#454a58", "w": "#8fd3ff"}, """
..y.y.y.y.y.y...
..gggggggggggg..
.ygGGGGGGGGGGgy.
..gGyyyGGyyyGg..
.ygGyKKKKKKyGgy.
..gGGKkkkkKGGg..
.ygGyKkwkkKyGgy.
..gGyKkkkkKyGg..
.ygGGKKKKKKGGgy.
..gGyyGGGGyyGg..
.ygGGGGGGGGGGgy.
..gggggggggggg..
..y.y.y.y.y.y...
"""),
    "stabilizer_coil": ({"e": "#22d3ee", "W": "#e0fbff", "r": "#4a4f5a", "c": "#a65a2c",
                         "C": "#e0874a"}, """
.......ee.......
......eWWe......
.......rr.......
.....CCCCCC.....
.....cccccc.....
.......rr.......
.....CCCCCC.....
.....cccccc.....
.......rr.......
.....CCCCCC.....
.....cccccc.....
.......rr.......
......eWWe......
.......ee.......
"""),
    "rift_capacitor": ({"m": "#4a4f5a", "n": "#a9afba", "v": "#4c1d95", "P": "#a855f7",
                        "w": "#f5e9ff"}, """
......nnnn......
.....mmmmmm.....
....mnnnnnnm....
....mvvvvvvm....
....mvPPPPvm....
....mvPPwPvm....
....mvPwPPvm....
....mvwwwPvm....
....mvPPwPvm....
....mvPwPPvm....
....mvvvvvvm....
....mnnnnnnm....
.....mmmmmm.....
"""),
    # ------------------------------------------------------------ recyclables
    "rusted_gear": ({"a": "#d08450", "b": "#9a5530", "c": "#6b3a22", "g": "#8a8f99"}, """
.......aa.......
...aa.abba.aa...
...abbbbbbbba...
....bbbccbbb....
..abbbc..cbbba..
.aabbc....cbbaa.
.aabgc....cbbaa.
..abbbc..cbgba..
....bbbccbbb....
...abbgbbbbba...
...aa.abba.aa...
.......aa.......
"""),
    "cracked_screen": ({"f": "#5b606b", "F": "#8b909a", "s": "#1d2b4a", "S": "#2d4a7a",
                        "w": "#dbe7ff"}, """
..FFFFFFFFFFFF..
..fssssssssssf..
..fsSSswSSSssf..
..fsSSSswSSssf..
..fsswwsswSssf..
..fsSssswwsssf..
..fsSSSswssssf..
..fssSswSSswsf..
..fssswSSsssws..
..fssssssssssf..
..ffffffffffff..
......ffff......
....FFFFFFFF....
"""),
    "dead_battery": ({"n": "#c9ccd3", "m": "#7c818c", "b": "#3c7a55", "B": "#55a676",
                      "d": "#2a5a3e", "k": "#22252c", "r": "#ef4444"}, """
.......nn.......
......mnnm......
.....bbbbbb.....
.....bBBBBd.....
.....bBBBBd.....
.....bBBBBd.....
.....kkkkkk.....
.....krkkkk.....
.....kkkkkk.....
.....bBBBBd.....
.....bBBBBd.....
.....bBBBBd.....
.....dddddd.....
"""),
    "shattered_lens": ({"m": "#6d7380", "g": "#bfe6f5", "q": "#6fb2d6", "w": "#ffffff"}, """
.....mmmmmm.....
....mggggggm....
...mgwwggggqm...
..mgwggwgggqqm..
..mggggwggqqqm..
..mgggggwwqqqm..
..mggggqqwqqqm..
..mgggqqqqwqqm..
...mgqqqqqqqm...
....mqqqqqqm....
.....mmmmmm.....
"""),
    "corrupted_drive": ({"k": "#3a3f4a", "n": "#8b909a", "a": "#c6cbd4", "d": "#9aa0ab",
                         "c": "#6d7380", "P": "#f472b6", "q": "#22d3ee"}, """
..kkkkkkkkkkkk..
..knnnnnnnnnnk..
..knnaaaaaannk..
..knaaddddaank..
.qknaddcccdankP.
..knadcPcdaaak..
..knaddcccdank..
..knaadddaaank..
.Pknnaaaaaannkq.
..knnnnnnnnnnk..
..knqqqPPPnnnk..
..kkkkkkkkkkkk..
"""),
    "broken_drone": ({"p": "#9aa0ab", "R": "#454a55", "l": "#5b606b", "b": "#2f3440",
                      "B": "#4a5162", "E": "#ef4444", "s": "#ffd24a"}, """
.ppp........ppp.
.pRp........pRp.
.ppp.l....l.ppp.
.....ll..ll.....
......bbbb......
.....bBEEBb.....
.....bBEEBb.....
......bbbb......
.....ll...l.....
.ppp.l.....s.s..
.pRp........s...
.ppp.......s.s..
"""),
    # --------------------------------------------------------------- trinkets
    "pixel_duck": ({"y": "#ffd93b", "Y": "#e0a800", "o": "#ff8a1f", "k": "#1f1f24"}, """
.....yyyy.......
....yyyyyy......
....yykyyy......
..ooyyyyyy......
..ooyyyyy.......
.....yyyyyyy..y.
...yyyyyyyyyyyy.
..yyyyyyyyyyyyy.
..yyyyYyyyyyyyy.
..yyyyyYYYYyyy..
...yyyyyyyyyy...
....YYYYYYYY....
"""),
    "lost_floppy": ({"b": "#2d5fd3", "B": "#1f3f99", "m": "#c6cbd4", "d": "#4a4f5a",
                     "w": "#f3f4f6", "r": "#ef4444"}, """
..bbbbbbbbbbb...
..bbmmmmmmmbbb..
..bbmmmdmmmbbb..
..bbmmmdmmmbbb..
..bbmmmmmmmbbb..
..bbbbbbbbbbbb..
..bbwwwwwwwwbb..
..bbwrrrrrrwbb..
..bbwwwwwwwwbb..
..bbwrrrrwwwbb..
..bbwwwwwwwwbb..
..BBBBBBBBBBBB..
"""),
    "static_radio": ({"a": "#a9afba", "r": "#8a5a3b", "R": "#6b4329", "k": "#2a2d36",
                      "g": "#5b606b", "w": "#f5c542"}, """
.........a......
........a.......
.......a........
..rrrrrrrrrrrr..
..rkkkkkkrrrrr..
..rkgkgkkrwwrr..
..rkkgkgkrrrrr..
..rkgkgkkrwwrr..
..rkkgkgkrrrrr..
..rkkkkkkrrrrr..
..RRRRRRRRRRRR..
...RR......RR...
"""),
    "frozen_clock": ({"i": "#bfefff", "I": "#7fd0f0", "c": "#d9a21e", "w": "#f4f7fb",
                      "k": "#2a2d36"}, """
.....iiiiii.....
....iccccccI....
...icwwwwwwcI...
..icwwwkwwwwcI..
..icwwwkwwwwcI..
..icwwwkwwwwcI..
..icwwwkkkwwcI..
..icwwwwwwwwcI..
..icwwwwwwwwcI..
...icwwwwwwcI...
....IccccccI....
.....II.I.II....
......I...I.....
"""),
    "glitched_snow_globe": ({"g": "#d8f1ff", "s": "#7cc7f2", "w": "#ffffff", "t": "#2f8f55",
                             "P": "#f472b6", "b": "#6b4329", "B": "#8a5a3b"}, """
.....gggggg.....
....gsssswsg....
...gswsssssPg...
...gsssssswsg...
...gsssttsssg...
..Pgssttttssg...
...gsstttttsgP..
....gsssssssg...
....gggggggg....
...bbbbbbbbbb...
...bBBBBBBBBb...
...bbbbbbbbbb...
"""),
    "void_music_box": ({"n": "#c084fc", "l": "#4c1d95", "P": "#a855f7", "v": "#2a1150",
                        "b": "#3b2a20", "B": "#5a3f2e", "g": "#f5c542"}, """
...........n....
...........nn...
...........n.n..
.........nnn....
..llllllllnn....
..lPPPPPPPPl....
..lPvvvvvvPl....
..bbbbbbbbbbbb..
..bBBBBBBBBBBb..
..bBBgBBBBgBBb..
..bBBBBBBBBBBb..
..bbbbbbbbbbbb..
"""),
    "cursed_crown": ({"g": "#f5c542", "G": "#c98f12", "p": "#a855f7", "r": "#ef4444"}, """
..g....g....g...
..gg..ggg..gg...
..ggg.gpg.ggg...
..gggggggggggg..
..gGGGGGGGGGGg..
..gGpGGrGGpGGg..
..gGGGGGGGGGGg..
..gggggggggggg..
"""),
    "rift_idol": ({"p": "#6b21a8", "P": "#a855f7", "e": "#22d3ee", "g": "#c98f12",
                   "G": "#f5c542"}, """
.......pp.......
......pPPp......
......PeeP......
......pPPp......
.......pp.......
.....pPPPPp.....
....pPPPPPPp....
....pPpPPpPp....
.....pPPPPp.....
......pPPp......
.....gggggg.....
....gGGGGGGg....
....gggggggg....
"""),
    # ---------------------------------------------------------------- gadgets
    "frag_grenade": ({"m": "#a9afba", "r": "#c9ccd3", "g": "#3f6b2a", "G": "#5f9440"}, """
.......mm.r.....
......mmmr.r....
.......mm..r....
.....gggggg.....
....gGgGgGgg....
....GgGgGgGg....
...gGgGgGgGgg...
...GgGgGgGgGg...
...gGgGgGgGgg...
....GgGgGgGg....
....gGgGgGgg....
.....gggggg.....
"""),
    "smoke_grenade": ({"s": "#d6d9df", "m": "#8b909a", "k": "#4a4f5a", "w": "#f3f4f6",
                       "G": "#7a8290"}, """
.........ss.....
........s..s....
......mmsm......
......mmmm......
.....kkkkkk.....
.....kwwwwk.....
.....kkkkkk.....
.....kGGGGk.....
.....kGGGGk.....
.....kGGGGk.....
.....kGGGGk.....
.....kkkkkk.....
"""),
    "lure_beacon": ({"y": "#ffd24a", "Y": "#fff3b0", "m": "#6d7380", "o": "#d9a21e",
                     "O": "#f5c542"}, """
.....y......y...
....y..yyyy..y..
....y.yYYYYy.y..
.....y.YYYY.y...
........mm......
.......mmmm.....
......oooooo....
.....oOOOOOOo...
.....oOOOOOOo...
.....oOOOOOOo...
......oooooo....
"""),
    "snap_hook": ({"m": "#6d7380", "M": "#c9ccd3", "r": "#b88a55"}, """
..........mm....
.........mMm....
........mMm.....
.......mMm......
..m...mMm...m...
..mm.mMm...mm...
...mmMMm..mm....
....mMMMmmm.....
....mMMMMm......
.....mmmm.......
....r...........
...r............
..r.............
"""),
    "barricade_kit": ({"m": "#5b606b", "p": "#7c3aed", "P": "#b388ff", "w": "#efe5ff",
                       "y": "#f5c542"}, """
..mmmmmmmmmmmm..
..mppppppppppm..
..mpPPPPPPPPpm..
..mpPwPPPPPPpm..
..mpPPPPPPPPpm..
..mmmmmmmmmmmm..
..mppppppppppm..
..mpPPPPPPPPpm..
..mpPwPPPPPPpm..
..mpPPPPPPPPpm..
..mmmmmmmmmmmm..
..yy........yy..
"""),
    "pulse_mine": ({"c": "#22d3ee", "C": "#9df3ff", "w": "#ffffff", "m": "#4a4f5a",
                    "M": "#7c818c", "y": "#f5c542", "k": "#2a2d36"}, """
......cccc......
....ccCwwCcc....
...cmmmmmmmmc...
..mmMMMMMMMMmm..
..mMMyMMMMyMMm..
..mmMMMMMMMMmm..
...mmmmmmmmmm...
....kkkkkkkk....
"""),
    "bandage": ({"w": "#f3f4f6", "W": "#c9ccd3", "r": "#ef4444"}, """
.....wwwwww.....
....wWWWWWWw....
...wWwwwwwwWw...
...wWwwrrwwWw...
...wWwrrrrwWw...
...wWwwrrwwWw...
...wWwwwwwwWw...
....wWWWWWWw....
.....wwwwwww....
..........www...
...........ww...
"""),
    "adrenaline_shot": ({"k": "#c9ccd3", "m": "#6d7380", "Y": "#facc15", "y": "#fde68a"}, """
..............k.
.............k..
............k...
...........mm...
..........mYym..
.........mYYym..
........mYYym...
.......mYYym....
......mYYym.....
.....mYYym......
....mmmmm.......
...mm...........
..mm............
.mm.............
"""),
    "secure_pouch": ({"b": "#8a5a3b", "l": "#5a3a24", "L": "#8a5a3b", "g": "#f5c542",
                      "k": "#2a2d36"}, """
......bbbb......
.....b....b.....
....llllllll....
...lLLLLLLLLl...
..lLLLLLLLLLLl..
..lLLLggLLLLLl..
..lLLLgkgLLLLl..
..lLLLLgLLLLLl..
..lLLLLLLLLLLl..
...lLLLLLLLLl...
....llllllll....
"""),
}

BLUEPRINT = """
..nnnnnnnnnnnn..
..nbbbbbbbbbbn..
..nbwbbwbbwbbn..
..nbbbbbbbbbbn..
..nbwwwwwwwbbn..
..nbwbbbbbwbbn..
..nbwbwwwbwbbn..
..nbwbbbbbwbbn..
..nbwwwwwwwbbn..
..nbbbbbbbbbbn..
..nnnnnnnnnnnn..
..rr........rr..
"""
for rarity, (dark, light) in RARITY_TINT.items():
    SPRITES[f"blueprint_{rarity}"] = ({"n": dark, "b": "#1e4f9c", "w": "#cfe4ff", "r": light}, BLUEPRINT)


def hex_rgba(h):
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), 255)


def draw(palette, art):
    rows = [r for r in art.strip("\n").split("\n")]
    if len(rows) > 16 or any(len(r) > 16 for r in rows):
        raise SystemExit(f"sprite too big: {len(rows)} rows / {max(map(len, rows))} cols")
    top = (16 - len(rows) + 1) // 2
    img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch != ".":
                px[x, y + top] = hex_rgba(palette[ch])
    # Outline: every transparent pixel touching the sprite gets a dark shade of it.
    out = img.copy()
    op = out.load()
    for y in range(16):
        for x in range(16):
            if px[x, y][3]:
                continue
            near = [px[nx, ny] for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1))
                    if 0 <= nx < 16 and 0 <= ny < 16 and px[nx, ny][3]]
            if near:
                r, g, b, _ = near[0]
                op[x, y] = (int(r * 0.28), int(g * 0.28), int(b * 0.3), 255)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=PACK)
    ap.add_argument("--sheet")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    images = {}
    for name, (palette, art) in SPRITES.items():
        images[name] = draw(palette, art)
        images[name].save(os.path.join(args.out, f"{name}.png"))
    if args.sheet:
        cols, cell = 9, 150
        rows = (len(images) + cols - 1) // cols
        sheet = Image.new("RGBA", (cols * cell, rows * (cell + 22)), (38, 38, 46, 255))
        d = ImageDraw.Draw(sheet)
        for i, (name, im) in enumerate(images.items()):
            x, y = (i % cols) * cell, (i // cols) * (cell + 22)
            sheet.alpha_composite(im.resize((128, 128), Image.NEAREST), (x + 11, y + 6))
            d.text((x + 6, y + 138), name, fill=(220, 220, 230, 255))
        sheet.save(args.sheet)
    print(f"{len(images)} textures -> {args.out}")


if __name__ == "__main__":
    main()
