#!/usr/bin/env python3
"""Draw the Raider Rank tier icons (nametag/tab glyphs E060-E067).

  bronze silver gold platinum  -> shields of increasing detail
  diamond                      -> cut gem
  grandmaster                  -> crown
  celestial                    -> radiant star
  eternity                     -> infinity ring

Each icon is a 16x16 ASCII map (D dark, M mid, L light, H highlight,
A accent, W white) coloured from a per-tier palette, with a dark outline
added automatically. Nexo scales them to the glyph height in theglitch.yml.

Usage: python scripts/gen-rank-icons.py [--preview out.png]
"""
import argparse
import os

from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "server", "plugins", "Nexo", "pack", "external_packs", "Oraxen",
                   "assets", "minecraft", "textures", "glyphs")
EDGE = (20, 16, 24, 255)

SHIELD = """
................
..MMMMMMMMMMMM..
..MLLLLLLLLLLM..
..MLHHLLLLLLLM..
..MLHLLLLLLLDM..
..MLLLLLLLLLDM..
..MLLLLLLLLLDM..
..MLLLLLLLLLDM..
..MLLLLLLLLDDM..
...MLLLLLLLDM...
...MLLLLLLDDM...
....MLLLLLDM....
.....MLLLDM.....
......MLDM......
.......MM.......
................
"""
SHIELD_CHEVRON = """
................
..MMMMMMMMMMMM..
..MLLLLLLLLLLM..
..MLHHLLLLLLLM..
..MLHLLLLLLLDM..
..MALLLLLLLADM..
..MLAALLLLAADM..
..MLLLAALAALDM..
..MLLLLAAALDDM..
...MLLLLALLDM...
...MLLLLLLDDM...
....MLLLLLDM....
.....MLLLDM.....
......MLDM......
.......MM.......
................
"""
SHIELD_STAR = """
................
..MMMMMMMMMMMM..
..MLLLLLLLLLLM..
..MLHHLLALLLLM..
..MLHLLAAALLDM..
..MLAAAAAAAADM..
..MLLAAAAAALDM..
..MLLLAAAALLDM..
..MLLAALLAALDM..
...MLALLLLALM...
...MLLLLLLDDM...
....MLLLLLDM....
.....MLLLDM.....
......MLDM......
.......MM.......
................
"""
SHIELD_WINGS = """
................
.A..MMMMMMMM..A.
AA..MLLLLLLM..AA
AAA.MLHHLLLM.AAA
.AAAMLHLLALMAAA.
..AAMLLLAAAMAA..
...AMLLAAAAMA...
....MLLLAALDM...
....MLLLLLLDM...
.....MLLLLDM....
.....MLLLLDM....
......MLLDM.....
......MLDDM.....
.......MDM......
........M.......
................
"""
GEM = """
................
................
....MMMMMMMM....
...MHLLHLLLDM...
..MHHLLHLLLDDM..
.MMMMMMMMMMMMMM.
.MHLLLHLLLLLDDM.
..MHLLHLLLLLDM..
...MHLHLLLLDM...
....MHHLLLDM....
.....MHLLDM.....
......MHDM......
.......MM.......
................
................
................
"""
CROWN = """
................
................
.A.....A.....A..
.M....MLM....M..
.MM..MLLLM..MM..
.MLM.MLHLM.MLM..
.MLLMLLHLLMLLM..
.MLLLLLLLLLLLM..
.MLALLLALLLALM..
.MLLLLLLLLLLDM..
.MMMMMMMMMMMMM..
.MHHLLLLLLLDDM..
.MMMMMMMMMMMMM..
................
................
................
"""
STAR = """
.......A........
.......A........
......MLM.......
......MHM.......
A....MLHLM....A.
.AMMMLLHLLMMMA..
..MLLLHWHLLLM...
...MLLHHHLLM....
....MLLHLLM.....
....MLLLLLM.....
...MLLMMMLLM....
...MLM...MLM....
..MLM.....MLM...
..MM.......MM...
.A...........A..
................
"""
INFINITY = """
.......A........
......AWA.......
.......A........
..MMMM...MMMM...
.MHHLLM.MLLLLM..
MHM..MLMLM..MLM.
ML....MLM....LM.
ML....MLM....DM.
MLM..MLMLM..MDM.
.MLLLLM.MLLLDM..
..MMMM...MMMM...
................
.A...........A..
AWA.........AWA.
.A...........A..
................
"""

TIERS = {  # name -> (map, palette {D,M,L,H,A,W})
    "bronze": (SHIELD, dict(D=(110, 60, 30), M=(150, 85, 40), L=(196, 122, 64), H=(236, 176, 120),
                            A=(120, 70, 35), W=(255, 255, 255))),
    "silver": (SHIELD_CHEVRON, dict(D=(110, 116, 128), M=(140, 148, 160), L=(190, 198, 210),
                                    H=(245, 248, 255), A=(70, 78, 98), W=(255, 255, 255))),
    "gold": (SHIELD_STAR, dict(D=(170, 110, 20), M=(205, 145, 30), L=(245, 196, 60), H=(255, 240, 160),
                               A=(255, 250, 215), W=(255, 255, 255))),
    "platinum": (SHIELD_WINGS, dict(D=(60, 140, 150), M=(80, 170, 180), L=(160, 225, 225),
                                    H=(235, 255, 255), A=(200, 240, 245), W=(255, 255, 255))),
    "diamond": (GEM, dict(D=(30, 120, 190), M=(40, 150, 220), L=(90, 205, 250), H=(210, 245, 255),
                          A=(255, 255, 255), W=(255, 255, 255))),
    "grandmaster": (CROWN, dict(D=(140, 20, 40), M=(190, 30, 50), L=(235, 70, 80), H=(255, 170, 170),
                                A=(255, 205, 60), W=(255, 255, 255))),
    "celestial": (STAR, dict(D=(110, 60, 190), M=(140, 90, 230), L=(185, 150, 255), H=(230, 215, 255),
                             A=(255, 225, 120), W=(255, 255, 255))),
    "eternity": (INFINITY, dict(D=(150, 30, 120), M=(210, 50, 160), L=(255, 110, 200), H=(255, 210, 240),
                                A=(255, 200, 70), W=(255, 255, 255))),
}


def draw(ascii_map, pal):
    rows = [r for r in ascii_map.strip("\n").split("\n")]
    im = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    px = im.load()
    for y, row in enumerate(rows[:16]):
        for x, ch in enumerate(row[:16]):
            if ch in pal:
                px[x, y] = pal[ch] + (255,)
    # auto outline: transparent pixels touching a filled one become EDGE
    filled = {(x, y) for x in range(16) for y in range(16) if px[x, y][3]}
    for x in range(16):
        for y in range(16):
            if (x, y) in filled:
                continue
            if any((x + dx, y + dy) in filled for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))):
                px[x, y] = EDGE
    return im


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    icons = {n: draw(m, p) for n, (m, p) in TIERS.items()}
    for name, im in icons.items():
        im.save(os.path.join(OUT, f"rank_t_{name}.png"))
    if args.preview:
        from PIL import ImageDraw
        scale = 8
        cell = 16 * scale + 24
        sheet = Image.new("RGBA", (cell * len(icons), cell + 30), (48, 52, 60, 255))
        d = ImageDraw.Draw(sheet)
        for i, (name, im) in enumerate(icons.items()):
            sheet.alpha_composite(im.resize((16 * scale, 16 * scale), Image.NEAREST), (i * cell + 12, 12))
            d.text((i * cell + 12, cell + 6), name.capitalize(), fill=(240, 240, 240, 255))
        # nametag-size strip: icons at real ~9px height next to fake text
        sheet.save(args.preview)
    print(f"{len(icons)} rank icons -> {OUT}")


if __name__ == "__main__":
    main()
