#!/usr/bin/env bash
#
# The Glitch — build the tutorial world (host only, once; safe to re-run with --rebuild).
#   sudo ./scripts/setup-tutorial.sh [--rebuild]
#
# Copies a 240x240 slice of Eleria (chosen with scripts/tutorial-slice-survey.py: driest,
# some cover, gentle hills) into a void world "tutorial" generated by GlitchWorldGen, so
# everything outside the slice is void behind a barrier wall. The licensed map stays on
# the host — nothing from it goes into git.

set -euo pipefail

SLICE_CX=-72
SLICE_CZ=-88
SLICE_SIZE=240
WORLD=tutorial
SRC=glitch_red_eleria

SERVER_DIR="/opt/theglitch/server"
DIM="${SERVER_DIR}/hub/dimensions/minecraft/${WORLD}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mc() { python3 "${SCRIPT_DIR}/mc-cmd.py" "$*"; }
log() { echo -e "\033[1;32m[tutorial]\033[0m $*"; }
die() { echo -e "\033[1;31m[tutorial]\033[0m $*" >&2; exit 1; }

[[ ${EUID} -eq 0 ]] || die "Run me with sudo"
REBUILD=false
[[ "${1:-}" == "--rebuild" ]] && REBUILD=true

if mc "mv info ${WORLD}" | grep -qi "spawn location"; then
  ${REBUILD} || die "World ${WORLD} already exists — pass --rebuild to recreate its terrain"
else
  log "Creating void world ${WORLD} (GlitchWorldGen)"
  rm -f "${SERVER_DIR}/plugins/GlitchWorldGen/${WORLD}.keep"
  mc "mv create ${WORLD} normal --generator GlitchWorldGen --no-structures"
  sleep 3
fi

log "Unloading ${WORLD} to copy the slice"
mc "mv unload ${WORLD} --remove-players hub"
sleep 3
rm -rf "${DIM}/region" "${DIM}/entities" "${DIM}/poi"
python3 "${SCRIPT_DIR}/tutorial-world.py" --cx "${SLICE_CX}" --cz "${SLICE_CZ}" --size "${SLICE_SIZE}" --src "${SRC}" --dst "${WORLD}"
chown -R minecraft:minecraft "${DIM}" "${SERVER_DIR}/plugins/GlitchWorldGen"

log "Loading ${WORLD}"
mc "mv load ${WORLD}"
sleep 3

log "Rules: no natural spawns, fixed noon, keep inventory, no weather"
for rule in "keep_inventory true" "spawn_mobs false" "advance_time false" "advance_weather false" \
            "mob_griefing false" "spawn_monsters false" "spawn_wandering_traders false" "spawn_patrols false"; do
  mc "execute in minecraft:${WORLD} run gamerule ${rule}" || true
done
mc "execute in minecraft:${WORLD} run time set 6000"
mc "execute in minecraft:${WORLD} run weather clear"
mc "execute in minecraft:${WORLD} run worldborder center ${SLICE_CX} ${SLICE_CZ}"
mc "execute in minecraft:${WORLD} run worldborder set $((SLICE_SIZE - 4))"
mc "mv modify ${WORLD} set difficulty normal" || true
mc "mv modify ${WORLD} set allow-flight false" || true

log "WorldGuard: nobody builds or breaks in the tutorial"
for flag in "build deny" "block-break deny" "block-place deny" "creeper-explosion deny" "tnt deny" \
            "fire-spread deny" "item-frame-rotation deny" "ride deny"; do
  mc "rg flag __global__ -w ${WORLD} ${flag}" || true
done

log "Done. Next: /tutorial admin autolayout (sets the step points), then /tutorial admin status"
