#!/usr/bin/env bash
#
# The Glitch — Phase 4.6: Set up WorldGuard regions + MythicMobs spawners
# for the dungeon shell at Slot 1.
# Run AFTER build-dungeon-slot1.sh + server restart:
#   sudo ./scripts/setup-dungeon-regions.sh
#
# WorldGuard region definitions are created via RCON (region-file seeding).
# MythicMobs spawner configurations are synced from the repo.
#
# NOTE: WorldGuard's /rg define command requires a player session (not RCON).
#       This script pre-seeds the regions.yml file directly, which takes
#       effect on the next server restart. Alternative: run the in-game
#       commands listed at the end of this script.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER_DIR="/opt/theglitch/server"
MC_USER="minecraft"

mc() { python3 "${REPO_DIR}/scripts/mc-cmd.py" "$@"; }

log()  { echo -e "\033[1;36m[regions]\033[0m $*"; }
warn() { echo -e "\033[1;33m[regions]\033[0m $*"; }
die()  { echo -e "\033[1;31m[regions]\033[0m $*" >&2; exit 1; }

[[ ${EUID} -eq 0 ]] || die "Run with sudo: sudo ./scripts/setup-dungeon-regions.sh"

# --- preflight ---------------------------------------------------------------
log "Checking server is up..."
mc "list" >/dev/null 2>&1 || die "Server not responding — is it running?"

# --- WorldGuard region seeding -----------------------------------------------
# Paper 26.x stores glitch_pve as a dimension of hub:
#   server/hub/dimensions/minecraft/glitch_pve/worldguard/regions.yml
WG_DIR="${SERVER_DIR}/hub/dimensions/minecraft/glitch_pve/worldguard"
REGIONS_FILE="${WG_DIR}/regions.yml"

log "Seeding WorldGuard regions for Slot 1"

# Create directory if it doesn't exist
mkdir -p "${WG_DIR}"

# If regions.yml exists, back it up
if [[ -f "${REGIONS_FILE}" ]]; then
  cp "${REGIONS_FILE}" "${REGIONS_FILE}.bak.$(date +%s)"
  log "Backed up existing regions.yml"
fi

# Generate regions.yml with slot protection
# Slot 1: (-1048, -58, -1048) to (-1001, -9, -1001)
# WorldGuard uses min/max in the format: 'x,y,z'
cat > "${REGIONS_FILE}" <<'YAML'
# The Glitch — WorldGuard regions for glitch_pve
# Auto-generated by setup-dungeon-regions.sh
# Takes effect on next server restart (or /rg reload in-game)

regions:
  # Slot 1: The Echoing Vault
  pve_slot1:
    type: cuboid
    min: '-1048,-64,-1048'
    max: '-1001,320,-1001'
    flags:
      block-break: deny
      block-place: deny
      # Inherit from __global__: pvp deny, chest-access allow, enderpearl deny

  # Staging area protection
  staging:
    type: cuboid
    min: '-24,-64,-24'
    max: '23,320,23'
    flags:
      block-break: deny
      block-place: deny
      pvp: deny
      enderpearl: deny
YAML

chown "${MC_USER}:${MC_USER}" "${REGIONS_FILE}"
chmod 644 "${REGIONS_FILE}"
log "Regions file written to ${REGIONS_FILE}"

# --- MythicMobs spawner configs ---------------------------------------------
log "Syncing MythicMobs spawner configurations"

# Create Spawners directory
MM_SPAWN_DIR="${SERVER_DIR}/plugins/MythicMobs/Spawners"
mkdir -p "${MM_SPAWN_DIR}"

# Slot 1 spawners: main hall + boss room
cat > "${MM_SPAWN_DIR}/Slot1_Spawners.yml" <<'YAML'
# The Glitch — MythicMobs Spawners for Slot 1: The Echoing Vault
# Spawn zones tied to dungeon shell at (-1024, -1024)

# Main Hall spawners (east + west alcoves)
Slot1_MainHall_West:
  MobName: GlitchStalker
  MobLevel: 1
  SpawnRange: 8
  SpawnAmount: 2
  Cooldown: 30
  CooldownMessage: '<red>Spawners recharging...'
  Conditions:
  - mmoconditions{conditions="myspawnid>0"} true
  - mythicconditions{conditions="mobcount<6"} true

Slot1_MainHall_East:
  MobName: GlitchPhantom
  MobLevel: 1
  SpawnRange: 8
  SpawnAmount: 1
  Cooldown: 45
  CooldownMessage: '<red>Spawners recharging...'
  Conditions:
  - mmoconditions{conditions="myspawnid>0"} true
  - mythicconditions{conditions="mobcount<6"} true

# Boss Room spawner (GlitchBrute as mini-boss)
Slot1_BossRoom:
  MobName: GlitchBrute
  MobLevel: 1
  SpawnRange: 12
  SpawnAmount: 1
  Cooldown: 120
  CooldownMessage: '<red>The boss is respawning...'
  Conditions:
  - mmoconditions{conditions="myspawnid>0"} true
  - mythicconditions{conditions="mobcount<2"} true
YAML

chown "${MC_USER}:${MC_USER}" "${MM_SPAWN_DIR}/Slot1_Spawners.yml"
chmod 644 "${MM_SPAWN_DIR}/Slot1_Spawners.yml"
log "Spawner configs written"

# --- MythicMobs mob spawn areas (coordinate-based) ---------------------------
log "Configuring spawn areas"

MM_AREAS_DIR="${SERVER_DIR}/plugins/MythicMobs/SpawnAreas"
mkdir -p "${MM_AREAS_DIR}"

cat > "${MM_AREAS_DIR}/Slot1_SpawnAreas.yml" <<'YAML'
# The Glitch — Spawn Areas for Slot 1: The Echoing Vault
# These define where mobs can spawn within the dungeon shell

Slot1_MainHall_West:
  Type: WORLD
  World: glitch_pve
  Area: CUBOID
  Min: '-1045,-57,-1036'
  Max: '-1042,-57,-1028'
  SpawnLimit: 4
  SpawnCooldown: 30
  Mobs:
  - GlitchStalker{lv=1} @0.7
  - GlitchPhantom{lv=1} @0.3

Slot1_MainHall_East:
  Type: WORLD
  World: glitch_pve
  Area: CUBOID
  Min: '-1007,-57,-1036'
  Max: '-1004,-57,-1028'
  SpawnLimit: 4
  SpawnCooldown: 30
  Mobs:
  - GlitchStalker{lv=1} @0.6
  - GlitchPhantom{lv=1} @0.4

Slot1_BossRoom:
  Type: WORLD
  World: glitch_pve
  Area: CUBOID
  Min: '-1032,-57,-1045'
  Max: '-1016,-57,-1004'
  SpawnLimit: 2
  SpawnCooldown: 120
  Mobs:
  - GlitchBrute{lv=1} @1.0
YAML

chown "${MC_USER}:${MC_USER}" "${MM_AREAS_DIR}/Slot1_SpawnAreas.yml"
chmod 644 "${MM_AREAS_DIR}/Slot1_SpawnAreas.yml"
log "Spawn areas written"

# --- hCaptureEvent extraction point for dungeon -----------------------------
log "Configuring dungeon extraction point"

CAPTURE_DIR="${SERVER_DIR}/plugins/hCaptureEvent/captures"
mkdir -p "${CAPTURE_DIR}"

cat > "${CAPTURE_DIR}/dungeon_x1_slot1.yml" <<'YAML'
# The Glitch — Extraction Point for Slot 1: The Echoing Vault
# Located in the boss room center, players channel to bank shards

DungeonX1:
  # WorldGuard region name (must match /rg define output)
  region: "dungeon_x1_slot1"
  world: "glitch_pve"
  # Capture time (seconds) — shorter than Red Zone (easier dungeon)
  capture-time: 8
  # Boss bar during capture
  boss-bar:
    enabled: true
    color: PURPLE
    style: SEGMENTED_8
    title: "<purple>Extracting from the Vault..."
  # Action bar
  action-bar:
    enabled: true
    message: "<purple>Extracting... <white>{progress}%</white>"
  # Reward on completion
  commands:
    - "eco give {player} 30"
    - "msg {player} &aVault extraction complete! +30 Glitch Shards banked."
  # Cancel if player leaves region
  cancel-on-leave: true
  # Cancel on damage
  cancel-on-damage: false
YAML

chown "${MC_USER}:${MC_USER}" "${CAPTURE_DIR}/dungeon_x1_slot1.yml"
chmod 644 "${CAPTURE_DIR}/dungeon_x1_slot1.yml"
log "Dungeon extraction point configured"

# --- Summary -----------------------------------------------------------------
cat <<'EOF'

============================================================
  Dungeon regions + spawners configured for Slot 1.
============================================================

  WorldGuard Regions (seeded to regions.yml):
    pve_slot1:  (-1048,-64,-1048) to (-1001,320,-1001)
                block-break: deny, block-place: deny
    staging:    (-24,-64,-24) to (23,320,23)
                block-break: deny, block-place: deny, pvp: deny

  MythicMobs Spawners:
    Slot1_MainHall_West:  GlitchStalker x2 (30s cooldown)
    Slot1_MainHall_East:  GlitchPhantom x1 (45s cooldown)
    Slot1_BossRoom:       GlitchBrute x1 (120s cooldown)

  hCaptureEvent:
    DungeonX1: Boss room extraction beacon (8s channel, 30 shards)

  IMPORTANT: Restart the server to load the new regions:
    sudo systemctl restart theglitch

  Verify in-game:
    scripts/mc-cmd.py 'mv tp <YourName> glitch_pve'
    Then run: /rg list
    And: /rg info pve_slot1

  To reload WorldGuard without restart:
    /rg reload

  To test spawners, kill existing mobs and wait for cooldown.

  Next: Phase 5.4 (custom dungeon plugin) for party system + run manager.
============================================================
EOF
