#!/usr/bin/env python3
"""Copy a square slice of a red map into the tutorial world (host only, server-side files).

Only the slice's chunks are written (region, entities and poi files), so every other
chunk of the tutorial world is generated by GlitchWorldGen as void with a barrier wall
facing the slice. Also writes plugins/GlitchWorldGen/tutorial.keep (the slice chunks).

Run with the tutorial world UNLOADED (mv unload tutorial), then mv load it.

  python3 tutorial-world.py --cx -72 --cz -88 --size 240 [--src glitch_red_eleria] [--dst tutorial]
"""
import argparse
import os
import re
import struct

ROOT = "/opt/theglitch/server/hub/dimensions/minecraft"
KEEP = "/opt/theglitch/server/plugins/GlitchWorldGen"
COORD = re.compile(r"r\.(-?\d+)\.(-?\d+)\.mca$")


def copy_dir(src_dir, dst_dir, chunks):
    """Write new .mca files holding only `chunks` (sector data copied verbatim)."""
    if not os.path.isdir(src_dir):
        return 0
    os.makedirs(dst_dir, exist_ok=True)
    by_region = {}
    for cx, cz in chunks:
        by_region.setdefault((cx >> 5, cz >> 5), []).append((cx, cz))
    copied = 0
    for (rx, rz), cs in by_region.items():
        src = os.path.join(src_dir, f"r.{rx}.{rz}.mca")
        if not os.path.isfile(src):
            continue
        data = open(src, "rb").read()
        if len(data) < 8192:
            continue
        header = bytearray(8192)
        body = bytearray()
        sector = 2
        for cx, cz in sorted(cs):
            i = (cx & 31) + (cz & 31) * 32
            loc = data[i * 4:i * 4 + 4]
            if loc == b"\0\0\0\0":
                continue
            off = int.from_bytes(loc[:3], "big") * 4096
            count = loc[3]
            blob = data[off:off + count * 4096]
            if len(blob) < 5:
                continue
            header[i * 4:i * 4 + 3] = sector.to_bytes(3, "big")
            header[i * 4 + 3] = count
            header[4096 + i * 4:4096 + i * 4 + 4] = data[4096 + i * 4:4096 + i * 4 + 4]  # timestamp
            body += blob.ljust(count * 4096, b"\0")
            sector += count
            copied += 1
        with open(os.path.join(dst_dir, f"r.{rx}.{rz}.mca"), "wb") as fh:
            fh.write(header + body)
    return copied


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cx", type=int, required=True)
    ap.add_argument("--cz", type=int, required=True)
    ap.add_argument("--size", type=int, default=240)
    ap.add_argument("--src", default="glitch_red_eleria")
    ap.add_argument("--dst", default="tutorial")
    a = ap.parse_args()
    half = a.size // 2
    x0, x1 = (a.cx - half) >> 4, (a.cx + half - 1) >> 4
    z0, z1 = (a.cz - half) >> 4, (a.cz + half - 1) >> 4
    chunks = [(x, z) for x in range(x0, x1 + 1) for z in range(z0, z1 + 1)]
    for sub in ("region", "entities", "poi"):
        n = copy_dir(os.path.join(ROOT, a.src, sub), os.path.join(ROOT, a.dst, sub), chunks)
        print(f"{sub}: {n} chunks copied")
    os.makedirs(KEEP, exist_ok=True)
    with open(os.path.join(KEEP, a.dst + ".keep"), "w") as fh:
        fh.writelines(f"{x} {z}\n" for x, z in chunks)
    print(f"{len(chunks)} slice chunks x {x0 * 16}..{x1 * 16 + 15} z {z0 * 16}..{z1 * 16 + 15} -> {a.dst}.keep")


if __name__ == "__main__":
    main()
